### ISSUE TITLE
Allow disabling auto-formatting in Go

### ISSUE THREAD

**Issue by reid47** [luan/nvim#35]
Our team has encountered a lot of frustration when working in Go due to the auto-formatter. It works very quickly and seems to add a new operation to the undo stack. It often ends up formatting too soon (e.g. after pasting a block of code, or in the middle of writing an import line) and then it becomes difficult to undo (because it just keeps coming back).

Is there a way to disable it? Can we add one? Wanted to get your thoughts. Thanks!

Side note: We have also noticed that the `.` shortcut (redo the last operation) does not seem to work. We aren't sure if this is related to the auto-formatting or not. Happy to open another issue for that if it's unrelated.

**Comment by luan** [comment]
Are you saying that it's running without you triggering it with a save? Do you have auto saving enabled?

It really should only trigger on save, which would let you get around the frustrations by saving less often / not suring those particular actions.

The `.` issue is related to this, I just created https://github.com/neoclide/coc.nvim/issues/1965 to see if they can address it there. For the time being, https://github.com/luan/nvim/commit/89916fa333c21f7077341fe8526cead3888261a4 should help.

---------

About not auto-formatting/importing: if you were to disable that, you would make it so your Go development environment behaved differently than what I consider is standard, most people I've interacted with expect a Go development environment to do that these days, on Vim or otherwise. If you still believe that is the correct choice for your team, you can tweak the variables on that commit above, or (for after coc.nvim formatting is back) disable it's `augroup` from this one: https://github.com/luan/nvim/commit/86aceb76a3914987cc635cc326a1b286f0c93a5d by re-defining it locally (in your user settings) and having only the `autocmd!` line inside to clear everything out.

**Comment by reid47** [comment]
Thank you for the response!

Yeah, I guess it's probably formatting on save and auto-saving quickly. I think we like the auto-save, so we may try to figure out how to decouple the two in our local settings.

Feel free to close this issue whenever! Mainly wanted to ask for your thoughts.

**Comment by luan** [comment]
Fixed in https://github.com/luan/nvim/commit/437f496a8861910d031481d59f9ca7c8fa18dc1b
